language: ruby
sudo: false

rvm:
- 2.2.5

cache:
  - bundler
  - npm

before_script:
 - chmod +x ./script/cibuild

script: ./script/cibuild

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true